# Copyright (c) 2022 Espresso Systems (espressosys.com)
# This file is part of the HotShot Query Service library.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program. If not,
# see <https://www.gnu.org/licenses/>.

[advisories]
ignore = [
    # remove_dir_all (used by deprecated tempdir crate)
    "RUSTSEC-2023-0018",
    # DoS in WebPKI that comes with tide_disco
    "RUSTSEC-2023-0052",
    # Tungstenite allows remote attackers to cause a denial of service
    # Dependency of async-tungstenite -> tide-websockets / surf-disco
    "RUSTSEC-2023-0065",
    # Unfixed "Marvin" vulnerability in `RSA`, unused in sqlite dependency
    "RUSTSEC-2023-0071",
    # Unfixed vulnerability in `rustls`, dependency of Tide
    "RUSTSEC-2024-0336",
]
