#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod erc1967_proxy;
pub mod fee_contract;
pub mod hot_shot;
pub mod i_plonk_verifier;
pub mod light_client;
pub mod light_client_mock;
pub mod light_client_state_update_vk;
pub mod light_client_state_update_vk_mock;
pub mod plonk_verifier;
pub mod shared_types;
