@startuml
skinparam componentStyle rectangle

component "zkSync Smart Contract" as SmartContract
component "eth_sender" as EthSender
component "L1" as L1
component "eth_watch" as EthWatch

component "Sequencer" as Sequencer
component "VM" as VM
database "Mempool" as Mempool

component "Witness Generator" as WitnessGenerator

component "API Server" as APIServer

APIServer --> Mempool: txn for submission

EthSender --> SmartContract: txn

L1 --> EthWatch: priority requests

Mempool --> Sequencer: pending txn
Sequencer -> VM: txn for execution
Sequencer <- VM: block-ready txn

Sequencer --> WitnessGenerator: sealed blocks

package "Prover" as Prover {
  component "Prover application" as ProverApp
}

WitnessGenerator -> ProverApp: witness
@enduml