# Copyright (c) 2022 Espresso Systems (espressosys.com)
# This file is part of the HotShot Query Service library.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program. If not,
# see <https://www.gnu.org/licenses/>.

[meta]
FORMAT_VERSION = "0.1.0"
NAME = "hotshot-status"
DESCRIPTION = """
Node-specific state and uncommitted data.

Unlike the availability and node APIs, which deal only with committed data (albeit with different
consistency properties), the status API offers a glimpse into internal consensus state and
uncommitted data. Here you can find low-level information about a particular node, such as consensus
and networking metrics. 

The status API is intended to be a lightweight way to inspect the activities and health of a
consensus node. It is the only API that can be run without any persistent storage, and its memory
overhead is also very low. As a consequence, it only serves two types of data:
* snapshots of the state right now, with no way to query historical snapshots
* summary statistics
"""

[route.block_height]
PATH = ["/block-height"]
DOC = """
Get the height of the latest committed block.
"""

[route.success_rate]
PATH = ["/success-rate"]
DOC = """
Get the view success rate.

Returns the fraction of views which resulted in a committed block, as a floating point number.
"""

[route.time_since_last_decide]
PATH = ["/time-since-last-decide"]
DOC = """
Get the time elapsed since the last decided time.

Returns the time elapsed in seconds since the Unix epoch.
"""

[route.metrics]
PATH = ["/metrics"]
METHOD = "METRICS"
DOC = """
Prometheus endpoint exposing various consensus-related metrics.
"""
