#![allow(clippy::all)]
//! This module contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod bls_sig;
pub mod bls_test;
pub mod bn254;
pub mod bn256g2;
pub mod bytes_lib;
pub mod counter;
pub mod dai;
pub mod deposit_contract;
pub mod deposit_contract_mock;
pub mod emergency_manager;
pub mod erc20_permit_mock;
pub mod erc20_weird_metadata;
pub mod example_rollup;
pub mod example_rollup_test;
pub mod global_exit_root_lib;
pub mod hot_shot;
pub mod hot_shot_test;
pub mod i_base_polygon_zk_evm_global_exit_root;
pub mod i_bridge_message_receiver;
pub mod i_hot_shot;
pub mod i_polygon_zk_evm_bridge;
pub mod i_polygon_zk_evm_errors;
pub mod i_polygon_zk_evm_global_exit_root;
pub mod i_verifier_rollup;
pub mod lib_note;
pub mod matic;
pub mod pairing;
pub mod polygon_zk_evm;
pub mod polygon_zk_evm_bridge;
pub mod polygon_zk_evm_bridge_mock;
pub mod polygon_zk_evm_global_exit_root;
pub mod polygon_zk_evm_global_exit_root_l2;
pub mod polygon_zk_evm_global_exit_root_l2_mock;
pub mod polygon_zk_evm_global_exit_root_mock;
pub mod polygon_zk_evm_mock;
pub mod polygon_zk_evm_timelock;
pub mod safe_math;
pub mod send_data;
pub mod shared_types;
pub mod token_wrapped;
pub mod uni;
pub mod utils;
pub mod verifier;
pub mod verifier_rollup_helper_mock;
