@startuml
component "HotShot Sequencer" as Seq

component "Example Rollup" as Rollup {
        component "API" as API
        component Executor as Exec {
            component Prover as Prover
        }

    }

package "Layer 1" as L1 {
    component "Sequencer Contract" as Seq_L1
    component "Rollup 1\nContract" as Rollup_L1
   
}

Alice -up-> API
note right of link
1. Submit transaction
end note


API -> Seq
note top of link
2. Forward transaction
end note

Seq -down-> Seq_L1
note right of link
3. Post block commitment
end note

Seq <-down- Exec
note right of link
4. Fetch block commitment
end note

Exec -> API
note right of link
5. Fetch transaction data
end note

Exec -> Rollup_L1
note right of link
6. Post proof
end note

Seq_L1 -> Rollup_L1
note bottom of link
7. Fetch block commitment
end note

Bob -down-> API
note right of link
8. Query balance
end note

' Layout
API -[hidden]r-> Exec
Rollup -[hidden]d-> L1
Alice -[hidden]r-> Bob
Seq -[hidden]d-> Rollup
@enduml