@startuml
!pragma teoz true
actor User

box rollup #LightYellow
    participant "API\n(RPC)" as rpc
    participant "Prover" as rprover
    participant "Executor" as executor
    participant Proposer
    participant Challenger
end box

box "Ethereum L1" #LightGrey
    participant "Rollup\nContract" as RC
    participant "Light\nClient\nContract" as LC
    participant "Fee\nContract" as fee
end box

box Espresso Sequencer Network #MistyRose
    box Sequencer Node #Bisque
        box APIs #LightCyan
            participant "Submit\nAPI" as submit
            participant "Query\nAPI" as query
        end box
        participant "HotShot\nEvents\nStream" as events
        participant "Validated\nState" as ValidatedState
        participant "State\nSigner" as signer
    end box

    participant Builder
    participant "HotShot\nLeader" as leader
    participant CDN
    participant Libp2p
    participant "HotShot\nreplicas" as replicas
    participant "HotShot\nstate\nrelay\nservice" as relay
    participant "HotShot\nstate\nprover\nservice" as prover
end box

group 1. Fee deposit
    Builder -> fee: fee deposit
end group

group 2. Transaction submisssion
    User -> rpc: rollup transaction
    rpc -> submit: transaction
    events -> Builder: transactions
end group

group 3. Leader obtains Espresso block
    Builder -> leader: available blocks
    leader -> Builder: claim block
end group

group 4. HotShot consensus
    leader <-> replicas: consensus messages
    & leader <-> Libp2p:
    & Libp2p <-> replicas:
    & replicas -> CDN:
    fee -> ValidatedState: credit fee deposit
    ValidatedState -> ValidatedState: apply header\ncharge fee
end group

group 5. Rollup block production
    query -> executor: Espresso header,\ntransactions in namespace
    executor -> executor: verify\nnamespace\nproof
    executor -> rprover: rollup block
end group

group 6. HotShot proving
    signer -> relay: state, signature
    relay -> prover: state,\nsignature bundle
    prover -> "Light\nClient\nContract" as LC: proof
    LC -> LC: verify
end group

group 7. Rollup proving
    rprover -> RC: rollup state proof

    group verify
        LC -> "Rollup\nContract" as RC: HotShot\ncommitment
    end group
end group

group 8. Rollup dispute
    Challenger -> RC: start dispute
    loop until dispute resolved
    Proposer -> RC: continue dispute
    LC --> RC: HotShot\ncommitment
    Challenger -> RC: continue dispute
end group
@enduml
