@startuml


[Collect & Filter] as CF
[COMMs Equivalence] as CE
[AND] as AND

[zkVM] as ZK

blk_cm_old --> CF
blk_cm_new --> CF
"<b>PROOF_TXS_HISTORY_ESP</b>" --> CF
"<b>ROLLUP_TXS</b>" --> CE
"<b>ROLLUP_TXS</b>" --> ZK

cm_txs_rollup --> CE
"<b>cm_txs_history</b>" --> CE
"<b>cm_txs_history</b>" --> CF

"cm_state_vm i" --> ZK
"cm_state_vm i+1" --> ZK
cm_txs_rollup --> ZK


ZK --> AND
CE --> AND
CF --> AND

AND --> OUTPUT


@enduml
