@startuml


[Espresso Derivatoin] as ED
[AND] as AND

[zkVM] as ZK

blk_cm_root --> ED
"<b>TXS_NAMESPACE_PROOFS</b>" --> ED
"<b>ROLLUP_TXS</b>" --> ED
"<b>ROLLUP_TXS</b>" --> ZK

cm_txs_rollup --> ED

"cm_state_vm i" --> ZK
"cm_state_vm i+1" --> ZK
cm_txs_rollup --> ZK


ZK --> AND
ED --> AND

AND --> OUTPUT


@enduml
