@startuml


[Collect & Filter] as CF
[COMMs Equivalence] as CE
[AND] as AND

[zkVM] as ZK

BLOCK_COMM_ESP_OLD --> CF
BLOCK_COMM_ESP_NEW --> CF
"<b>PROOF_TXS_HISTORY_ESP</b>" --> CF
"<b>ROLLUP_TXS</b>" --> CE
"<b>ROLLUP_TXS</b>" --> ZK

COMM_TXS_ROLLUP --> CE
"<b>COMM_TXS_HISTORY_ESP</b>" --> CE
"<b>COMM_TXS_HISTORY_ESP</b>" --> CF

"COMM_STATE_VM i" --> ZK
"COMM_STATE_VM i+1" --> ZK
COMM_TXS_ROLLUP --> ZK


ZK --> AND
CE --> AND
CF --> AND

AND --> OUTPUT


@enduml
