#![allow(unused_imports, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod erc1967proxy;
pub mod feecontract;
pub mod iplonkverifier;
pub mod lightclient;
pub mod lightclientarbitrum;
pub mod lightclientmock;
pub mod permissionedstaketable;
pub mod plonkverifier;
pub mod plonkverifier2;
pub mod staketable;
