# Copyright (c) 2022 Espresso Systems (espressosys.com)
# This file is part of the HotShot Query Service library.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program. If not,
# see <https://www.gnu.org/licenses/>.

[package]
name = "hotshot-query-service"
version = "0.1.76"
authors = ["Espresso Systems <hello@espressosys.com>"]
edition = "2021"
license = "GPL-3.0-or-later"

[features]
default = ["file-system-data-source", "metrics-data-source", "sql-data-source"]

# Enables support for an embedded SQLite database instead of PostgreSQL.
# Ideal for lightweight nodes that benefit from pruning and merklized state storage,
# offering advantages over file system storage.
embedded-db = []

# Enable the availability data source backed by the local file system.
file-system-data-source = ["atomic_store"]

# Enable a lightweight data source for status APIs without the archival availability API.
metrics-data-source = []

# Enable the availability data source backed by a Postgres database.
sql-data-source = ["include_dir", "refinery", "refinery-core", "sqlx", "log"]

# Enable extra features useful for writing tests with a query service.
testing = [
    "espresso-macros",
    "hotshot-example-types",
    "portpicker",
    "rand",
    "spin_sleep",
    "tempfile",
    "sql-data-source",
    "file-system-data-source"
]

[[example]]
name = "simple-server"
required-features = ["sql-data-source", "testing"]

[dependencies]
anyhow = { workspace = true }
ark-serialize = { workspace = true }
async-lock = { workspace = true }
async-trait = { workspace = true }
backoff = "0.4"
bincode = { workspace = true }
chrono = "0.4"
committable = { workspace = true }
custom_debug = "0.6"
derivative = { workspace = true }
derive_more = { workspace = true }
either = "1.12"
futures = { workspace = true }
hotshot = { git = "https://github.com/EspressoSystems/HotShot.git", tag = "0.5.84" }
hotshot-testing = { git = "https://github.com/EspressoSystems/HotShot.git", tag = "0.5.84" }
hotshot-types = { git = "https://github.com/EspressoSystems/HotShot.git", tag = "0.5.84" }
itertools = "0.12.1"
jf-merkle-tree = { version = "0.1.0", git = "https://github.com/EspressoSystems/jellyfish", tag = "0.4.5", features = [
    "std",
] }
jf-vid = { version = "0.1.0", git = "https://github.com/EspressoSystems/jellyfish", tag = "0.4.5", features = [
    "std",
    "parallel",
] }
lazy_static = "1"
prometheus = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snafu = "0.8"
surf-disco = "0.9"
tagged-base64 = "0.4"
tide-disco = "0.9"
time = "0.3"
tokio = { version = "1", default-features = false, features = [
    "rt-multi-thread",
    "macros",
    "parking_lot",
    "sync",
] }
toml = "0.8"
tracing = "0.1"
tracing-subscriber = "0.3"
trait-variant = "0.1"
typenum = "1"
url = "2"
vbs = "0.1"
vec1 = "1.12"

# Dependencies enabled by feature "file-system-data-source".
atomic_store = { git = "https://github.com/EspressoSystems/atomicstore.git", tag = "0.1.4", optional = true }

# Dependencies enabled by feature "sql-data-source".
include_dir = { version = "0.7", optional = true }
log = { version = "0.4", optional = true }
refinery = { version = "0.8", features = ["tokio-postgres"], optional = true }
refinery-core = { version = "0.8", optional = true }
sqlx = { version = "0.8", features = [
    "bit-vec",
    "postgres",
    "runtime-tokio",
    "sqlite",
    "tls-native-tls",
], optional = true }

# Dependencies enabled by feature "testing".
espresso-macros = { git = "https://github.com/EspressoSystems/espresso-macros.git", tag = "0.1.0", optional = true }
hotshot-example-types = { git = "https://github.com/EspressoSystems/HotShot.git", tag = "0.5.84", optional = true }
portpicker = { version = "0.1", optional = true }
rand = { version = "0.8", optional = true }
spin_sleep = { version = "1.2", optional = true }
tempfile = { version = "3.10", optional = true }

# Dependencies enabled by feature "backtrace-on-stack-overflow".
#
# This feature allows unit tests to print out a backtrace if they overflow their stack. The
# implementation may trigger undefined behavior, so it is only used in tests and requires its own
# separate feature flag; it is not enabled just by using the "testing" feature.
#
# This feature is not supported on Windows because it uses Unix-style signal handling to catch
# stack overflow exceptions.
[target.'cfg(not(windows))'.dependencies]
backtrace-on-stack-overflow = { version = "0.3", optional = true }

[dev-dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
espresso-macros = { git = "https://github.com/EspressoSystems/espresso-macros.git", tag = "0.1.0" }
generic-array = "0.14"
hotshot-example-types = { git = "https://github.com/EspressoSystems/HotShot.git", tag = "0.5.84" }
portpicker = "0.1"
rand = "0.8"
reqwest = "0.12.3"
spin_sleep = "1.2"
tempfile = "3.10"
