#!/usr/bin/env bash
#
# Used to build docker images in a quick way for local testing.
#
# On Linux:
#
#   - Native executables are built and patched to run inside docker.
#   - Expected to be run in nix-shell or nix develop because it requires patchelf
#     to be installed.
#
# On Darwin: the build is done inside a docker container.
#
# Usage: scripts/build-docker-images-native
#
set -euo pipefail

# Check kernel
case $(uname -s) in
  Linux)
    KERNEL=linux
    ;;
  Darwin)
    KERNEL=darwin
    ;;
  *)
    echo "This script is only supported on Linux and Darwin"
    exit 1
    ;;
esac

# Check architecture
case $(uname -m) in
  x86_64)
    ARCH=amd64
    PLATFORM=linux/amd64
    INTERPRETER=/lib64/ld-linux-x86-64.so.2
    ;;
  arm64)
    ARCH=arm64
    PLATFORM=linux/arm64
    ;;
  *)
    echo "Machine type $(uname -m) is not supported."
    exit 1
    ;;
esac

# Compile binaries
case $KERNEL in
  linux)
    cargo build --release
    ;;
  darwin)
  # Use a different target directory for docker builds to avoid conflicts with
  # native builds.
  CARGO_TARGET_DIR=target/docker

  # Build in docker container:
  #   - RUSTFLAGS is needed for compilation.
  #   - CARGO_TARGET_DIR is set to point to the location where the hosts
  #     CARGO_TARGET_DIR is mounted.
  #   - PWD is mounted to /work.
  #   - Cargo registry and git directory are mounted to avoid re-downloading
  #     dependencies.
  docker run \
    -e RUSTFLAGS \
    -e CARGO_TARGET_DIR=/work/target/docker \
    -v "$(pwd):/work" \
    -v "$CARGO_HOME/registry:/usr/local/cargo/registry" \
    -v "$CARGO_HOME/git:/usr/local/cargo/git" \
    -it ghcr.io/espressosystems/devops-rust:stable \
    bash -c "cd /work && cargo build --release"
    ;;
esac

# Copy binaries to a temporary directory.
WORKDIR=$(mktemp -d -t espresso-docker-build-XXXXXXXX)

trap "exit" INT TERM
trap cleanup EXIT
cleanup(){
    rm -rfv "${WORKDIR}"
}

mkdir -p "${WORKDIR}/target/$ARCH/release"
for binary in "orchestrator" "cdn-broker" "cdn-marshal" "cdn-whitelist" "sequencer" "commitment-task" "submit-transactions" "reset-storage" "state-relay-server" "state-prover" "deploy" "keygen" "permissionless-builder" "nasty-client" "pub-key" "espresso-dev-node"; do
  cp -v "${CARGO_TARGET_DIR}/release/$binary" "${WORKDIR}/target/$ARCH/release"
  # Patch the interpreter for running without nix inside the ubuntu based docker image.
  if [ $KERNEL == "linux" ]; then
    patchelf --set-interpreter "$INTERPRETER" "${WORKDIR}/target/$ARCH/release/$binary"
  fi
done

# Copy the dev-node launch script
cp -v scripts/launch-dev-node-with-postgres ${WORKDIR}

# Download the latest foundry binary and extract anvil for the dev-node docker image.
curl -L https://github.com/foundry-rs/foundry/releases/download/nightly/foundry_nightly_linux_${ARCH}.tar.gz -o ${WORKDIR}/foundry.tar.gz
tar -xzvf ${WORKDIR}/foundry.tar.gz -C ${WORKDIR}/target/$ARCH/release anvil


export DOCKER_BUILDKIT=1
docker build --platform $PLATFORM -t ghcr.io/espressosystems/espresso-sequencer/orchestrator:main -f docker/orchestrator.Dockerfile ${WORKDIR}
docker build --platform $PLATFORM -t ghcr.io/espressosystems/espresso-sequencer/cdn-broker:main -f docker/cdn-broker.Dockerfile ${WORKDIR}
docker build --platform $PLATFORM -t ghcr.io/espressosystems/espresso-sequencer/cdn-marshal:main -f docker/cdn-marshal.Dockerfile ${WORKDIR}
docker build --platform $PLATFORM -t ghcr.io/espressosystems/espresso-sequencer/cdn-whitelist:main -f docker/cdn-whitelist.Dockerfile ${WORKDIR}
docker build --platform $PLATFORM -t ghcr.io/espressosystems/espresso-sequencer/state-relay-server:main -f docker/state-relay-server.Dockerfile ${WORKDIR}
docker build --platform $PLATFORM -t ghcr.io/espressosystems/espresso-sequencer/prover-service:main -f docker/prover-service.Dockerfile ${WORKDIR}
docker build --platform $PLATFORM -t ghcr.io/espressosystems/espresso-sequencer/sequencer:main -f docker/sequencer.Dockerfile ${WORKDIR}
docker build --platform $PLATFORM -t ghcr.io/espressosystems/espresso-sequencer/commitment-task:main -f docker/commitment-task.Dockerfile ${WORKDIR}
docker build --platform $PLATFORM -t ghcr.io/espressosystems/espresso-sequencer/submit-transactions:main -f docker/submit-transactions.Dockerfile ${WORKDIR}
docker build --platform $PLATFORM -t ghcr.io/espressosystems/espresso-sequencer/deploy:main -f docker/deploy.Dockerfile ${WORKDIR}
docker build --platform $PLATFORM -t ghcr.io/espressosystems/espresso-sequencer/builder:main -f docker/permissionless-builder.Dockerfile ${WORKDIR}
docker build --platform $PLATFORM -t ghcr.io/espressosystems/espresso-sequencer/nasty-client:main -f docker/nasty-client.Dockerfile ${WORKDIR}
docker build --platform $PLATFORM -t ghcr.io/espressosystems/espresso-sequencer/espresso-dev-node:main -f docker/espresso-dev-node.Dockerfile ${WORKDIR}
