#!/usr/bin/env bash
set -euo pipefail

export PATH=./target/release:$PATH

ESPRESSO_BASE_STORAGE_PATH=$(mktemp -d -t espresso-XXXXXXXX)
export ESPRESSO_BASE_STORAGE_PATH
echo "Using sequencer storage path: $ESPRESSO_BASE_STORAGE_PATH"

# If keeping the storage path, is desired for debugging, comment out the line
# below or set a custom storage path in process-compose.yaml.
trap "exit" INT TERM
trap cleanup EXIT
cleanup(){
    echo "Cleaning up sequencer storage path: $ESPRESSO_BASE_STORAGE_PATH"
    rm -rv "$ESPRESSO_BASE_STORAGE_PATH"
}

process-compose "$@"
