#!/usr/bin/env python3
#
# This script takes the logs output by process-compose (formatted as JSON) and writes them in an
# easier-to-read plaintext format with colors.
#
# Usage (assuming `log_location: /tmp/pc.log` in `process-compose.yaml`:
#
# 	cat /tmp/pc.log | scripts/fmt-pc-logs > /tmp/formatted.log
#

import fileinput
import json

def main():
    for line in fileinput.input(encoding="utf-8"):
        obj = json.loads(line)
        if 'message' in obj:
            print(obj['process'] + '| ' + obj['message'])

if __name__ == '__main__':
    main()
