#!/usr/bin/env bash
# If ESPRESSO_SEQUENCER_LIGHTCLIENT_ADDRESS is unset and
# ESPRESSO_SEQUENCER_DEPLOY_LIGHTCLIENT_CONTRACT is "yes" or "1" the light
# client contract will be deployed. This feature is intended for demo or testnet
# purposes only.
set -eo pipefail

if [[ -z "${ESPRESSO_SEQUENCER_LIGHTCLIENT_ADDRESS}" ]]; then
  if [[ "${ESPRESSO_SEQUENCER_DEPLOY_LIGHTCLIENT_CONTRACT}" == "yes" || "${ESPRESSO_SEQUENCER_DEPLOY_LIGHTCLIENT_CONTRACT}" == "1" ]]; then
    echo "Light client contract address not found, deploying it now."
    gen-demo-contract --contracts-root-dir="./contracts"
    forge fmt
    forge build
    forge script DeployLightClientDemoScript --fork-url $ESPRESSO_SEQUENCER_L1_PROVIDER --broadcast
    ESPRESSO_SEQUENCER_LIGHTCLIENT_ADDRESS=$(cat contracts/broadcast/LightClientDemo.s.sol/*/run-latest.json | jq -r '.receipts[1].contractAddress')
    echo "Light client contract address: $ESPRESSO_SEQUENCER_LIGHTCLIENT_ADDRESS"
  else
    echo "ESPRESSO_SEQUENCER_LIGHTCLIENT_ADDRESS not provided and deployment is not enabled. Exiting."
    exit 1
  fi
fi

state-prover -d --light-client-address $ESPRESSO_SEQUENCER_LIGHTCLIENT_ADDRESS
