#!/usr/bin/env bash

set -e

# load env vars in .env
set -a; source .env; set +a;

SEQUENCER_API=http://localhost:$ESPRESSO_SEQUENCER_API_PORT
LOAD_GENERATOR=http://localhost:$ESPRESSO_SUBMIT_TRANSACTIONS_PORT
TIMEOUT=60

# Wait for the load generator to start.
while ! curl -s --fail $LOAD_GENERATOR/healthcheck > /dev/null; do
	echo "Waiting for demo to start"
	sleep 1
done

# Get the block height and number of transactions, wait some time, and check that these numbers have
# both increased.
block_height=`curl -s $SEQUENCER_API/node/block-height`
num_tx=`curl -s $SEQUENCER_API/node/transactions/count`

echo "Initial state:"
echo "  block_height: $block_height"
echo "  transactions: $num_tx"

# Bash magic to get the current time in seconds since start of this shell
START=$SECONDS

# Check blocks and transactions are increasing
# Every second until timeout after 60 seconds
while true; do
	new_block_height=`curl -s $SEQUENCER_API/node/block-height`
	new_num_tx=`curl -s $SEQUENCER_API/node/transactions/count`
	if [[ $new_block_height -gt $block_height && $new_num_tx -gt $num_tx ]]; then
		echo "Final state:"
		echo "  block_height: $new_block_height"
		echo "  transactions: $new_num_tx"
		echo "Block height and transaction count are increasing. Great!"
		break
	fi
	sleep 1
	if [[ $((SECONDS - START)) -gt $TIMEOUT ]]; then
		echo "Timeout waiting for block height and transaction count to increase"
		echo "Final state:"
		echo "  block_height: $new_block_height"
		echo "  transactions: $new_num_tx"

		if ! [[ $new_block_height -gt $block_height ]]; then
			echo "Block height is not increasing!"
		fi
		if ! [[ $new_num_tx -gt $num_tx ]]; then
			echo "Transaction count is not increasing!"
		fi

		exit 1
	fi
done

echo "Checking if builder is healthy at http://localhost:$ESPRESSO_BUILDER_SERVER_PORT"
curl -s --fail http://localhost:$ESPRESSO_BUILDER_SERVER_PORT > /dev/null

# TODO, uncomment: currently the healthcheck may hang for a long time if the prover
# is generating a proof. See https://github.com/EspressoSystems/espresso-sequencer/issues/1325
# echo "Checking if prover is healthy at http://localhost:$ESPRESSO_PROVER_SERVICE_PORT"
# curl -s --fail "http://localhost:$ESPRESSO_PROVER_SERVICE_PORT" > /dev/null
