#!/usr/bin/env bash
# This script is to test the installation instructions in doc/ubuntu.md without
# using Nix on ubuntu. It's not recommended to run it outside of a container or
# otherwise ephemeral environment like the CI.
set -e
#
# Execute the ubuntu installation instructions from doc/ubuntu.md
#
# Skip cloning the repo and changing directories, because we want to test with
# the current code and not what's in the main branch.
SCRIPT="$(grep '^    ' doc/ubuntu.md | sed 's/^    //' | sed 's/^cd .*//' | sed 's/^git clone .*//')"

# Remove sudo if we're already root
if [ "$(whoami)" == "root" ]; then
    SCRIPT="$(echo "$SCRIPT" | sed 's/^sudo //' | sed 's/| sudo /| /')"
fi

# Workaround: foundryup installs into XDG_CONFIG_HOME if that's set HOME otherwise.
export XDG_CONFIG_HOME=$HOME

echo "Will execute:"
echo "$SCRIPT"
echo

echo "$SCRIPT" | bash -exo pipefail
