[route.getfeebalance]
PATH = ["fee-balance/:height/:address"]
":height" = "Integer"
":address" = "Literal"
DOC = "Get current balance in fee state. Expected parameter is an Ethereum address in hex format."