name: Documentation
on:
  push:
    branches:
      - "main"
      - "release-*"
  pull_request:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ (github.ref == 'refs/heads/main' && github.run_number) || github.ref }}
  cancel-in-progress: true

env:
  RUSTFLAGS: --cfg async_executor_impl="async-std" --cfg async_channel_impl="async-std"
  RUSTDOCFLAGS: --cfg async_executor_impl="async-std" --cfg async_channel_impl="async-std"

jobs:
  doc:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Just
        run: sudo apt-get install -y just

      - uses: Swatinem/rust-cache@v2
        name: Enable Rust Caching

      - name: Build Docs
        run: |
          just doc

      - name: Create documentation
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          cp -R target/doc public
          echo '<meta http-equiv="refresh" content="0; url=sequencer">' > public/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: sequencer.docs.espressosys.com
